### ISSUE TITLE
papirus-write doesn't understand special characters

### ISSUE THREAD

**Issue by ungutknut** [PiSupply/PaPiRus#10]
When trying to output text containing ä ö ü (e.g. sudo papirus-write "ä") and most likely many more, wrong characters appear. Like when you choose a wrong charset.

Also I can't get a line break to work. \n doesn't seem to do the job.

**Comment by theooos** [comment]
Same issue with the line break. Any solution found?

**Comment by francesco-vannini** [comment]
The parsing of those escape character is not part of the current code implementation and needs refactoring of the code. I will investigate the issue regarding the lack of support for unicode.

**Comment by shawaj** [comment]
The line break issue mentioned by @theooos is currently being discussed by @francesco-vannini @BenScarb @shawaj in #68 

Still need to sort other bits

**Comment by cmseal** [comment]
Unicode support would be awesome, if possible...
Really love this project, and my Pi Zero W with PiPyRus is becoming so useful! :)

**Comment by shawaj** [comment]
Glad you think so :-)

**Comment by cyberscribe** [comment]
+1 for unicode or at least utf-8 support

**Comment by shawaj** [comment]
@cyberscribe - at the moment it's not particularly high on our priorities list for PaPiRus as we're a little over stretched at the moment.

Would welcome some community assistance on this and some of the other issues if there is anyone out there that can help :-)

**Comment by cyberscribe** [comment]
Is the driver a C/C++ module for Python, or is it written in pure Python?

**Comment by cyberscribe** [comment]
Sorry, I see you're wrapping PIL.ImageFont, which does look like it can support unicode if done properly: http://stackoverflow.com/a/22612295

**Comment by cyberscribe** [comment]
@shawaj if I were to augment PapirusText and PapirusTextPos to support utf-8 would you consider a pull request?

**Comment by shawaj** [comment]
Oh 100% yes :-)

The ePaper driver is written in C and is over at the RePaper/gratis repo.

Everything here is python or bash

**Comment by shawaj** [comment]
See #112

**Comment by francesco-vannini** [comment]
This is now solved in #112
