### ISSUE TITLE
Drive es133ut1

### ISSUE THREAD

**Issue by Etn40ff** [PiSupply/PaPiRus#102]
Hi,
I have a spare e-ink display I would like to play with. Can I use a PaPiRus Zero to control it?
Here is the full specification: http://www.good-display.com/downloadRepository/ef7cfdc2-9efe-4d02-b1e0-f583c02b8b06.pdf
Thanks

**Comment by shawaj** [comment]
You can try but it's unlikely to work. To start with it looks like a different connector.

We only support displays from Pervasive Displays at the moment.

Thanks

**Comment by Etn40ff** [comment]
Thanks,
sorry for the spam.

**Comment by shawaj** [comment]
@Etn40ff - it's not spam, no need to apologise :-)

Sorry we couldn't be of more help! Hope you manage to find a driver board for it. If you do find one, post the link here :-)
