### ISSUE TITLE
Papirus setup not working

### ISSUE THREAD

**Issue by myrdinwylt** [PiSupply/PaPiRus#113]
I recently purchased a papirus and have been trying to use it. There appears to be a problem when I setup the papirus though. After following the guide carefully the demos will not work. I am using a 2 inch papirus screen with a new raspi 0 w running rasbian jessie with pixel. When I do any demo a error like this appears.
```bash
pi@raspberrypi:~ $ sudo papirus-clock
Traceback (most recent call last):
  File "/usr/local/bin/papirus-clock", line 131, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/papirus-clock", line 74, in main
    papirus = Papirus()
  File "/usr/local/lib/python2.7/dist-packages/papirus/epd.py", line 58, in __init__
    self._lm75b = LM75B()
  File "/usr/local/lib/python2.7/dist-packages/papirus/lm75b.py", line 22, in __init__
    self._bus.write_byte_data(self._address, LM75B_CONF_REGISTER, LM75B_CONF_NORMAL)
IOError: [Errno 5] Input/output error
```
Reading the message and corresponding source files it appears to be some problem with the LM75B sensor. Please help me correct this error if you can.

**Comment by myrdinwylt** [comment]
@DAlperin

**Comment by myrdinwylt** [comment]
@DAlperin is working with me on this problem.

**Comment by DAlperin** [comment]
Due to the nature of the problem I am starting to think it is a hardware issue. The issue persists over multiple installs of the OS and software. Does that make any sense to you guys based on your knowledge of the hardware and software? Thanks!

**Comment by shawaj** [comment]
Did you turn on I2C and SPI?

What header have you soldered to the pi zero?

Is it the PaPiRus Zero?

Thanks

**Comment by DAlperin** [comment]
Hey thanks for the quick response. I am forced to wait until monday until I have the hardware again. (its at a sort of local makerspace) however I know it is PaPiRus Zero, I can not confirm the other to. I am really sorry to have to ask and then not be able to work on it for a bit. You can ignore this until I post here again. Im really really sorry again... Thanks for the help!

**Comment by myrdinwylt** [comment]
To answer your questions
 1. I am not aware of what 12c and SPI are
2. We have not soldered a header on but are attaching the pi and papirus with the stuctaral pins included in the box in away that allows the stacking headers to touch the pi. We are using generic stacking headers.
3. We are using the papyrus 0 2.0 inch

**Comment by DAlperin** [comment]
@myrdinwylt I think I enabled I2c and SPI. Also we are in fact using the PaPiRus Zero. Lets wait on this for now until we have access to the pi again. Thanks!

**Comment by francesco-vannini** [comment]
The errors you have @myrdinwylt are because the I2C and SPI aren't enabled. There is a section in the README.md which tells you how to manually enable I2C and SPI. This has however been automated in the latest commit.
For a brief time there was an issue with smbus not being installed automatically. This was needed by LM75B and it has now been included in the auto installation. In case you are not on the latest branch @stocktoncycles please run sudo apt-get install python-smbus which should fix your problems.

If you get confused what I suggest is to use a spare SD, flash the latest Raspbian and run the auto configuration once again. 
The post from our good friend Frederick is now outdated and issues about sudo are no longer current. Please disregard the majority of that article as the issues have now been fixed in the current branch.

**Comment by stocktoncycles** [comment]
@francesco-vannini , I'm sure it's possible that I2C and SPI we're not enabled though I did manually enable them in the config tool before re-starting the pi. I will check to see if smbus is installed. Thanks.

**Comment by francesco-vannini** [comment]
@stocktoncycles and  @myrdinwylt can you confirm whether you managed to make any progress on this? I don't think this is an issue though. I'll keep this open for a little while to give you time to get back.

**Comment by DAlperin** [comment]
Thank you guys for the help we will try you solutions on Monday and they all sound like they will work. Thanks!

**Comment by vanillabrand** [comment]
Hi i have the same problem. i've installed as instructed and enabled I2C & SPI but it's still showing me the same error. Is the error because it can't communicate with the screen? Help!

**Comment by shawaj** [comment]
@vanillabrand what is the error you are getting?

**Comment by vanillabrand** [comment]
Thanks @shawaj  
`pi@raspberrypi:~ $ sudo papirus-clock
Traceback (most recent call last):
  File "/usr/local/bin/papirus-clock", line 131, in <module>
    main(sys.argv[1:])
  File "/usr/local/bin/papirus-clock", line 74, in main
    papirus = Papirus()
  File "/usr/local/lib/python2.7/dist-packages/papirus/epd.py", line 58, in __init__
    self._lm75b = LM75B()
  File "/usr/local/lib/python2.7/dist-packages/papirus/lm75b.py", line 22, in __init__
    self._bus.write_byte_data(self._address, LM75B_CONF_REGISTER, LM75B_CONF_NORMAL)
IOError: [Errno 5] Input/output error`

I've tried installing manually too. Enabled SPI & I2C, installed everything using sudo but it still shows the same error. Any clues?

thanks!

**Comment by shawaj** [comment]
What's the result if you run `sudo i2cdetect -y 1` ?

**Comment by vanillabrand** [comment]
`
           0    1   2   3   4   5   6   7  8   9   a   b   c   d   e   f
00:                 -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
10:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60:       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70:       -- -- -- -- -- -- -- -- 
`

**Comment by francesco-vannini** [comment]
Can you please try on a different Raspberry Pi? Preferably one with a pre-soldered header. Which header did you use for your Pi Zero?

**Comment by vanillabrand** [comment]
Ah ok found the screen wasn't working. Got a new one on order. Thx

**Comment by shawaj** [comment]
@vanillabrand - the screen not working is very unlikely. We have had very few go wrong as they're tested in the factory.

What header are you using on the Pi Zero?

**Comment by vanillabrand** [comment]
It's pretty likely if it had a hairline crack running through it. New one
arrived and works a treat ;) thx

**Comment by shawaj** [comment]
@vanillabrand fantastic news!
