### ISSUE TITLE
colour e-paper possible?

### ISSUE THREAD

**Issue by ungutknut** [PiSupply/PaPiRus#116]
Hi,

there are these super cheap colour e-paper displays available on aliexpress:
https://de.aliexpress.com/item/2-7-Colorful-Epaper-Display-Panel-with-264x176-pixel/32672619894.html?scm=1007.13482.37805.0&pvid=4205c33d-b679-426d-b1dc-bb84df57249a&tpp=1

Would it be possible to drive those with the papirus?

**Comment by shawaj** [comment]
It would not be possible to drive that particular display, but we will have similar displays of our own soon... Up to 12" in size :-)

They will need a new driver board though
