### ISSUE TITLE
PaPiRus not rendering screen

### ISSUE THREAD

**Issue by tomaso909** [PiSupply/PaPiRus#121]
I am using the 2.7 screen Papirus on a PI 3. I had it working for a while but after an apt-get upgrade, it stopped working. I also fiddled a bit with the PI settings because I was trying to get a GPS connected with bit-banging on ports 22 and 4 to work, but I believe I have now set everything as it was before. Further, I reinstalled the drivers of this repo but it still does not work.

I do not get any error but the screen does not show anything. For example, running `papirus-clock` writes `panel = EPD 2.7 264 X 176 version=4 COG=2 FILM=231` in the terminal but the screen is empty.

Is there any tests I can perform? Any ideas are welcomed.

**Comment by francesco-vannini** [comment]
First of all I would recommend getting a spare SD card and install a fresh
Raspbian on it. Verify that all is well with PaPiRus then maybe use that
system as a baseline to understand what you changed on your current one
that made the board not work as it should.

**Comment by shawaj** [comment]
@tomaso909 did you manage to sort this?

**Comment by tomaso909** [comment]
Yes. It worked after a fresh install.
