### ISSUE TITLE
IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by eat-sleep-code** [PiSupply/PaPiRus#124]
I have a new Pi Zero W with the PaPiRus Zero.   When I run any of the command line items, I get an error similar to: 

> File "/usr/local/bin/papirus-clear", line 29 in <module> 
> main()
> File "/usr/local/bin/papirus-clear", line 23 in main
> papirus = Papirus()
> File "/usr/local/lib/python2.7/dist-packages/papirus/epd.py", line 58, in __init__
> self._lm75b = LM75B()
> File "/usr/local/lib/python2.7/dist-packages/papirus/lm75b.py", line 22, in __init__
> self._bus.write_byte_data(self._address, LM75B_CONF_REGISTER, LM75B_CONF_NORMAL)
> IOError: [Errno 121] Remote I/O error

The Pi Zero is running the latest version of Jessie Lite.

**Comment by tvoverbeek** [comment]
Smells like the Zero W cannot communicate with the lm75b temperature sensor via I2C.
Check I2C is enabled with raspi-config.
If enabled then use i2cdetect (from the i2c-tools package, install if not there) .
'i2cdetect -y 1' should report a device on address 0x48 (the lm75b). If not check the connections between the Zero W and Papirus Zero.

**Comment by shawaj** [comment]
@eat-sleep-code did you get this sorted?

**Comment by eat-sleep-code** [comment]
Yeah, apparently a bad solder job.   Went to hammerless headers and it is working.

**Comment by shawaj** [comment]
@eat-sleep-code you mean that you're now using the hammer header or were before? 

Because we've had issues with the hammer headers not getting a good connection previously. We recommend everyone to solder or buy one of our pre soldered Pi Zeros.

In any case, glad you've got it working

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/56006670-3a138980-5cac-11e9-96b9-584e6e42b535.png)
anyone

**Comment by MichaelSternNYC** [comment]
I was getting the same error message so, per the advice above, I revisited my solder joints and cleaned up anything that looked suspicious. I also took he opportunity to remove a small splatter of solder on the underside of the board. Victory! Test code is now running without error. The hardware does as it should; when I power the machine down, my test remains on the screen.

**Comment by shawaj** [comment]
@MichaelSternNYC thanks for the input. What was the solder spatter and what were the dodgy looking connections. Would be interesting to know for our reference and to improve manufacture quality

**Comment by MichaelSternNYC** [comment]
Not your lousy soldering — mine. I hadn’t done a great job putting headers on my Pi. 

Von meinem iPhone gesendet.

**Comment by shawaj** [comment]
Aha! Even better news 😁
