### ISSUE TITLE
turn into pip library

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#128]
turn into pip library

**Comment by shawaj** [comment]
Oops didn't realise this had already been mentioned

**Comment by shawaj** [comment]
See #74

**Comment by Minipada** [comment]
Hi, sorry for resurrecting an old issue, is there a plan on working on this?

**Comment by shawaj** [comment]
At some point, which is why we've left the old issue open, but we don't really have a timeline
