### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eat-sleep-code** [PiSupply/PaPiRus#134]
Is there any documentation to utilizing the buttons on the Zero display?

**Comment by tvoverbeek** [comment]
See https://github.com/PiSupply/PaPiRus/tree/master/hardware/PaPiRus%20Zero.

**Comment by eat-sleep-code** [comment]
Hmmm, didn't see anything there about how to detect a button press etc.

**Comment by tvoverbeek** [comment]
How to detect button presses you will find in any RaspBerryPi GPIO tutorial.
See also the papirus-buttons example (https://github.com/PiSupply/PaPiRus/blob/master/bin/papirus-buttons)
