### ISSUE TITLE
All scripts end in error: IOError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by f4exb** [PiSupply/PaPiRus#146]
Example:

sudo papirus-write "Hello, World!"
Traceback (most recent call last):
  File "/usr/local/bin/papirus-write", line 45, in <module>
    main()
  File "/usr/local/bin/papirus-write", line 39, in main
    text = PapirusTextPos(rotation=args.rotation)
  File "/usr/local/lib/python2.7/dist-packages/papirus/textpos.py", line 25, in __init__
    self.papirus = Papirus(rotation = rotation)
  File "/usr/local/lib/python2.7/dist-packages/papirus/epd.py", line 58, in __init__
    self._lm75b = LM75B()
  File "/usr/local/lib/python2.7/dist-packages/papirus/lm75b.py", line 22, in __init__
    self._bus.write_byte_data(self._address, LM75B_CONF_REGISTER, LM75B_CONF_NORMAL)
IOError: [Errno 121] Remote I/O error

**Comment by f4exb** [comment]
Well I looked at issue #124 (closed now) and eventually I got i2cdetect showing address 0x48. Then I got papirus-clock working.

I use a RPi2 with the 40 pin connector. I unplugged and re-plugged the Papirus maybe that did the trick.

**Comment by shawaj** [comment]
Have you enabled i2c and SPI?

**Comment by neuberfran** [comment]
![image](https://user-images.githubusercontent.com/38701397/56006691-4f88b380-5cac-11e9-94b8-632e5deb36c9.png)
anyone

**Comment by shawaj** [comment]
@neuberfan - are you using a PaPiRus?

**Comment by neuberfran** [comment]
yes, if I use 0x1b(7bits) works, but I need 0x36 (8bits)
![image](https://user-images.githubusercontent.com/38701397/56007431-11d95a00-5caf-11e9-964e-017fd975798f.png)

**Comment by shawaj** [comment]
What are you actually trying to do? And you are using a PaPiRus epaper display yes? 

Please start a new issue explaining what you are trying to do, what software you are using on your Pi, what version of the PaPiRus you have and what issues you are facing.

**Comment by tvoverbeek** [comment]
@neuberfran 8 bits addressing does not really exist in I2C.
The most significant 7 bits are the address and the least significant bit indicates write(0) or read(1).
So your 8-bits 0x36 is in fact a write to 7 bits address 0x1b.
Moreover the PaPiRus has nothing on address 0x1b. It uses SPI to drive the display. The HAT RTC uses (7-bits) I2c address 0x6f.
So you must have something else on address 0x1b. Hence not a PaPiRus issue at all
