### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PaPiRus#157]
![papirus](https://user-images.githubusercontent.com/16068311/30544688-3fa0b09c-9c7f-11e7-863f-5cfb64b9d668.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![papirus-github-banner](https://user-images.githubusercontent.com/1878314/73881257-e9cb7080-4857-11ea-8bb8-3d005c41bbac.png)
