### ISSUE TITLE
writing image to papirus

### ISSUE THREAD

**Issue by TS22082** [PiSupply/PaPiRus#163]
When using the code from the Readme:

`
from papirus import PapirusImage
img = PapirusImage(rotation = 180)

img.write('/path/to/my/image.bmp')
`

I keep getting the TypeError:
integer argument expected, got float

Any ideas? I know the papirus works because I was playing around with text output for awhile without any problems.

**Comment by tvoverbeek** [comment]
This is with Python 3?
Now fixed for Python 3 on github. See commit https://github.com/PiSupply/PaPiRus/commit/40a27224709ce9b79c4f8d886fa8f1dbf73cd0b0
