### ISSUE TITLE
PaPiRus Zero 5volt supply

### ISSUE THREAD

**Issue by uselesshippy** [PiSupply/PaPiRus#164]
The PaPiRus Zero pHat has a 5v supply listed, but as far as I can see from the schematics the 5v line is not used.

Can I omit this connection and still have the full functionality of the pHat?

I ask this as I want to drive the screen from an Arduino, and I only have 3.3v available.

Thanks

**Comment by tvoverbeek** [comment]
Should work. The 5V is only connected to the solder pad on the pHAT which normally is not used.
Waiting for Aaron or Francesco from Pi SUpply to confirm.

**Comment by shawaj** [comment]
You can see the datasheet here - https://github.com/PiSupply/PaPiRus/blob/master/hardware/PaPiRus%20Zero/Latest%20Version%20-%20v1.2/2015-032-01-PaPiRus-ZERO-circuit_v1_2.pdf

As you can see - the 5v is not used other than to breakout the 5v to the FPC extension connector on the PCB and for the 5v pad.

Hope that helps!

**Comment by uselesshippy** [comment]
That's what I thought, but I just wanted to check.

Thank you.
