### ISSUE TITLE
text.write - size and position?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#169]
Does this still work? If so add to readme

text.write(text, size, x,y)
text.write("hello world", 20, 10, 10 )

**Comment by tvoverbeek** [comment]
Yes and No.
Position is not available in the PapirusText, size, fontpath and maxLines are.
Will update README

**Comment by tvoverbeek** [comment]
README updated

**Comment by shawaj** [comment]
Thanks;
