### ISSUE TITLE
is root actually needed on all of these now?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#170]
is root actually needed on all of these now?

https://github.com/PiSupply/PaPiRus#manual-installation

**Comment by tvoverbeek** [comment]
Yes, when you put/copy/modify files outside your own directories you usually do not have access, so you must use sudo.
Will update manual installation by adding 'sudo' where needed

**Comment by tvoverbeek** [comment]
README updated

**Comment by shawaj** [comment]
Thanks Ton!
