### ISSUE TITLE
ImportError: cannot import name 'Papirus'

### ISSUE THREAD

**Issue by glitchedZap** [PiSupply/PaPiRus#174]
I installed the lib with the curl command.
In Python2 and 3 I can not import anything.
I for every module I get this error:
ImportError: cannot import name 'Papirus' / 'PapirusComposite' etc...
Anyone else have this issue?

**Comment by shawaj** [comment]
Is your Pi fully up to date and what OS are you using?

Thanks

**Comment by glitchedZap** [comment]
Got it.
I named my own programm „papirus.py“.
That caused the issue.
