### ISSUE TITLE
text.py wrong indentation

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PaPiRus#18]
the indentation of the snippet below is still not right. Am I missing something here?

```
else:
                # No space left on line so move to next one
text_lines.append("")
                current_line += 1
text_lines[current_line] += " " + word
```

**Comment by YoungAtHome** [comment]
Delete all characters to left of text including any (unexpanded) tabs and
hidden characters, and replace with the right amount of spaces.

Regards,
Nick

**Comment by francesco-vannini** [comment]
Thanks Nick, I get that. What I meant is to understand why had the file not been fixed yet. Forgive me I am pretty new to GitHub but it seems quite a trivial fix.

**Comment by shawaj** [comment]
This should be fixed now in the latest commit.

Can you try pulling down the latest code and testing it?

**Comment by shawaj** [comment]
@francesco-vannini @YoungAtHome - can you verify this is now working ok?

**Comment by shawaj** [comment]
Closing as this has been fixed.
