### ISSUE TITLE
Wrong font path

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/PaPiRus#21]
papirus-write under build/scripts-2.7/ still has the old font path

**Comment by shawaj** [comment]
Think that file is not used at all?

**Comment by francesco-vannini** [comment]
the files under build are used when setup is lunched. Removing the build folder before setup fixes the issue as a new build folder gets created with the correct files. I suspect that if a file is present it does not get overwritten.

**Comment by shawaj** [comment]
So it seems like the best thing to do is remove the build folder completely then as we update software here, new installs will get the correct build files?

**Comment by francesco-vannini** [comment]
Yes, it is working on my branch

**Comment by shawaj** [comment]
Can you do a PR on that then? As the one you have done only includes an update to the inheritance problem, not the removing of the build folder

**Comment by francesco-vannini** [comment]
I have created a PR but be careful as in the PR there is more than just the deletion of the build folder. There is also a review of the README and the text.py files.

**Comment by shawaj** [comment]
whats wrong with readme and text.py?

**Comment by shawaj** [comment]
@francesco-vannini is there still something wrong with readme and text.py?

If they are separate issues to this, could you put them in separate issues?
