### ISSUE TITLE
Open source hardware certification

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#216]
PaPiRus HAT certification
![OSHW_mark_UK000017](https://user-images.githubusercontent.com/3359418/94977161-70337180-050f-11eb-8533-b3ada29ae774.png)
[OSHW_mark_UK000017.pdf](https://github.com/PiSupply/PaPiRus/files/5320738/OSHW_mark_UK000017.pdf)

**Comment by shawaj** [comment]
PaPiRus Zero certification
![OSHW_mark_UK000018](https://user-images.githubusercontent.com/3359418/94977173-83ded800-050f-11eb-87c1-bcf16e75f057.png)
[OSHW_mark_UK000018.pdf](https://github.com/PiSupply/PaPiRus/files/5320741/OSHW_mark_UK000018.pdf)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000018](https://user-images.githubusercontent.com/1878314/95060263-f27b8b80-06f1-11eb-8deb-a61f0fd0abcd.png)

**Comment by ChristopherRush** [comment]
![OSHW_mark_UK000017](https://user-images.githubusercontent.com/1878314/95060522-46867000-06f2-11eb-9815-149abf83775c.png)
