### ISSUE TITLE
Screen status: Unsupported COG

### ISSUE THREAD

**Issue by yigitsengezer** [PiSupply/PaPiRus#229]
When i run papirus-system command i get "Unsupported Cog" error. I have raspberry pi zero w with pwnagotchi installed.

**Comment by tvoverbeek** [comment]
COG = Chip On Glass. It seems not to detect the expected EPD display.
How did you install the software drivers for the PaPiRus?
Pwnagorchi has its own code for PaPiRus, but you still need the device drivers.
Do /dev/epd and /dev/spi0.0 exist?

**Comment by yigitsengezer** [comment]
i installed with "curl -sSL https://pisupp.ly/papiruscode | sudo bash" command and it installed successfuly.
Yes /dev/epd exist but there is no /dev/spi0.0.
I have /dev/spidev0.0

**Comment by tvoverbeek** [comment]
That is my bad. /dev/spidev0.0 is correct.
What is the contents of /etc/default/epd-fuse?

**Comment by yigitsengezer** [comment]
```
# Default settings for epd-fuse file is sourced by /bin/sh from
# /etc/init.d/epd-fuse

# Options to pass to epd_fuse
#EPD_MOUNTPOINT=/dev/epd
EPD_SIZE=2.0
#EPD_OPTS='-o allow_other -o default_permissions'
```

**Comment by tvoverbeek** [comment]
That is as expected. The display is the 200x96 one (2.0 inch) which fits the pi zero w?
If so, check the papirus pHat is correctly conencted to the 40-pin header. It is easy to be off by 1 pin or 1 row.

**Comment by yigitsengezer** [comment]
Yes it is 2.0 inch. I soldered the pins today. I connected all 40 pins. If it's because of the pins I can solder it again.

**Comment by tvoverbeek** [comment]
That is the only thing I can think off right now. Please double check the solder connections.

**Comment by yigitsengezer** [comment]
Thank you very much, I will try it tomorrow and share the result.

**Comment by yigitsengezer** [comment]
I installed raspberry OS and the screen did not work again. Now I reinstalled pwnagotchi OS and the screen worked. I don't understand how it worked but it did. Thanks for everything.
