### ISSUE TITLE
About framebuffer mirror function

### ISSUE THREAD

**Issue by ooxx-tw** [PiSupply/PaPiRus#24]
Hi,
I need framebuffer mirror function.
But, I execute papirus-config and select Mirror Framebuffer no action.
Please provide a tutorial or methods.
Thanks...

**Comment by shawaj** [comment]
try typing `papirus-framepush` at the command line

**Comment by ooxx-tw** [comment]
Command not found and I can not find papirus-framepush in PiSupply/PaPiRus/bin on GitHub.

**Comment by shawaj** [comment]
Hmm that's odd! Will get it uploaded

**Comment by lbendlin** [comment]
Any idea when you will be able to upload this?

**Comment by ooxx-tw** [comment]
Mmm
Although the e-paper show slow response.
But I think the e-paper is to display clock and picture.
I need to synchronize LCD(Main) screen or became second screen.
And If the LCD screen sleep I can also see in the e-paper.

Other question:
I do not understand in the /dev/epd directory function.
This differs general LCD using the /dev/fbx.
Can you explain it?

/dev/epd/
├── BE
│   ├── current
│   ├── current_inverse
│   ├── display
│   └── display_inverse
├── command
├── current
├── current_inverse
├── display
├── display_inverse
├── LE
│   ├── current
│   ├── current_inverse
│   ├── display
│   └── display_inverse
├── panel
├── temperature
└── version


Thanks!

**Comment by ukscone** [comment]
I made a few notes on the meanings of the directories in /dev/epd last year. http://blog.burninghorse.com/2015/07/24/a-few-notes-on-papirus/ that info was origiannly from Adafruit

**Comment by ooxx-tw** [comment]
Hi shawaj,
Can you upload papirus-framepush?

**Comment by shawaj** [comment]
Closing this issue as it is covered in #71 already 

Still on the to do list.
