### ISSUE TITLE
Please use '/usr/bin/python2' instead of '/usr/bin/python'

### ISSUE THREAD

**Issue by guydunigo** [PiSupply/PaPiRus#26]
For Archlinux, 'python' means 'python3', so please use '/usr/bin/python2' instead of '/usr/bin/python' in the papirus scripts.

**Comment by shawaj** [comment]
@francesco-vannini @tvoverbeek do you know of a way whereby we could check for python version and server different code as a result? or would we just have to maintain to separate codebases?

**Comment by shawaj** [comment]
See #52 also

**Comment by guydunigo** [comment]
The problem is not about using python 3, I have both python2 and python3, it's just that /usr/bin/python is a link on linux but it can point to either /usr/bin/python3.x or /usr/bin/python2.x depending on the distro. (x being the installed version of python)
The thing is, there often is a link too named /usr/bin/python2 which always points towards /usr/bin/python2.x (available in raspbian too I think).
So for my issue, it is just about modifying #!/usr/bin/python to #!/usr/bin/python2.

**Comment by shawaj** [comment]
Yeah sure, but they're similar enough that we can deal with them together
in one issue. Will leave this closed for now :-)

Thanks for reporting it though

**Comment by shawaj** [comment]
Hey it wasn't even closed. We will leave it open for now then :-P

**Comment by tvoverbeek** [comment]
See the python2-and-3 branch which has modified code which will run under both Python2 and Python3. Branch will soon be merged into master.
