### ISSUE TITLE
error while starting a PaPirus Program (in epd.py, use tobytes() instead of tostring()).

### ISSUE THREAD

**Issue by guydunigo** [PiSupply/PaPiRus#27]
There is an error when I start any of the PaPiRus programs :
	In file '/usr/lib/python2.7/site-packages/papirus/epd.py', line 139 :
		tostring() has been removed, user tobytes() instead.
And if I change tostring() to tobytes(), it works.

**Comment by shawaj** [comment]
Fixed with latest commit
