### ISSUE TITLE
installation script error "error: file '/home/pi/PaPiRus/papirus-set' does not exist"

### ISSUE THREAD

**Issue by kurt77** [PiSupply/PaPiRus#28]
Am i the only one to receive this error:
error: file '/home/pi/PaPiRus/papirus-set' does not exist
after laubchibg the install script:
curl -sSL https://goo.gl/i1Imel | sudo bash
I've previously enabled the spi as requested.

**Comment by shawaj** [comment]
Try again now. The path to papirus-set was wrong.

Thanks

**Comment by shawaj** [comment]
Fix by changing path in setup.py to bin/papirus-set

**Comment by kurt77** [comment]
Thank you...but now i have another error:
copying and adjusting bin/papirus-draw -> build/scripts-2.7
error: file '/home/pi/PaPiRus/bin/papirus-tmp' does not exist
bash: line 10: papirus-setup: command not found

**Comment by kurt77** [comment]
there is another typo in papirus-setup:
bin/papirus-tmp
instead of
bin/papirus-temp
I could correct by myself in the git repo...but i'm not yet a git master...so i prefere you correct it.
Thanks
