### ISSUE TITLE
papirus-temp: missing packages

### ISSUE THREAD

**Issue by kurt77** [PiSupply/PaPiRus#30]
papirus-temp needs "bc" package in order to work...maybe it should be installed during the install process.
It's also missing i2cget

pi@raspberrypi:~/Code $ sudo papirus-temp
/usr/local/bin/papirus-temp: line 8: i2cget: command not found
/usr/local/bin/papirus-temp: line 14: -5: substring expression < 0
(standard_in) 1: syntax error
(standard_in) 1: syntax error
Temp is  deg C ( deg F).

**Comment by shawaj** [comment]
Can you make a pull request to fix these issues?

**Comment by kurt77** [comment]
done!

**Comment by shawaj** [comment]
Isn't i2c-tools installed by default in Raspbian? You just need to enable it from raspi-config I think?

**Comment by kurt77** [comment]
It wasnt installed on my raspbian.
And yes you have to enable it with raspi-config

**Comment by shawaj** [comment]
Fixed with #33
