### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by doody** [PiSupply/PaPiRus#31]
Hi,

I found that setup.py have a typo on which will cause install failed

scripts=['bin/papirus-clear', 'bin/papirus-write', 'bin/papirus-set', 'bin/papirus-gol', 'bin/papirus-clock', 'bin/papirus-config', 'bin/papirus-setup', 'bin/papirus-draw', 'bin/papirus-set', 'bin/papirus-tmp']

the last one should be 'bin/papirus-temp' 

or

change the filename from papirus-temp to papirus-tmp

Doody

**Comment by shawaj** [comment]
Just fixed this with PR #29
