### ISSUE TITLE
Calling tobytes() instead of tostring() in EPD.py display() function

### ISSUE THREAD

**Issue by doody** [PiSupply/PaPiRus#32]
Hi,

I found the following problem when I trying to use the display function

 File "/usr/local/lib/python2.7/dist-packages/papirus/epd.py", line 139, in display
    f.write(image.tostring())
 File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 699, in tostring
    "Please call tobytes() instead.")
Exception: tostring() has been removed. Please call tobytes() instead.

Compare to the EPD.py from RePaper, should be change to tobyte() instead

Thanks,
Doody

**Comment by shawaj** [comment]
Fixed with latest commit. Can you test and confirm?

**Comment by doody** [comment]
Yes, it works now 👍
