### ISSUE TITLE
Add note about enabling i2c to readme

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#34]
It tells you to enable SPI in readme but not i2c. Add note to fix this

**Comment by kurt77** [comment]
I needed to enable spi.
And for i2c i had to edit
/boot/cmdline.txt
and
/boot/config.txt
Maybe you can also use raspi-config

**Comment by ukscone** [comment]
enabling i2c is the same as for spi and in the same advanced menu in raspi-config

**Comment by shawaj** [comment]
yeah this was just a note to me really to not forget :-)

**Comment by francesco-vannini** [comment]
This has been added in the main README.md
