### ISSUE TITLE
Ruby support 

### ISSUE THREAD

**Issue by dsaito** [PiSupply/PaPiRus#35]
Hi. I'm very interested in Papirus E-ink display, and would like to know about potential support for Ruby in the near future. Thank you.

**Comment by shawaj** [comment]
We won't be supporting it officially but feel free to have a go and we will host the resulting codebase here gladly. You can just adapt the python code to ruby

**Comment by shawaj** [comment]
Closing this issue but let us know how you get on. Thanks

**Comment by shawaj** [comment]
Actually, on second thoughts will leave it open in case anybody wants to help you port over any code to ruby

**Comment by tvoverbeek** [comment]
See Issue #150. Closing this one.
