### ISSUE TITLE
Support for 10.2" Pervasive Displays (EZ102CT011)

### ISSUE THREAD

**Issue by edundias** [PiSupply/PaPiRus#36]
Hi,

I'm trying to connect a 10.2" display from Pervasive Displays (model EZ102CT011) and when I use the epd-fuse and set EPD_SIZE to 10.2 it does not work. 
I haven't been able to display anything. Can I request some support please?
Thank you very much in advance.

**Comment by shawaj** [comment]
You should post your issue on this GitHub repo - https://github.com/repaper/gratis

At the moment we can't support 10.2" because the driver code and waveforms are not open source. You should go to that GitHub page and ask them to open source them!
