### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by theooos** [PiSupply/PaPiRus#39]
Read a previously closed issue on this, however my problem still exists.

I'm having a strange bug with the papirus-buttons demo, and I assume it's down to the fact I'm using a Raspberry Pi 1B and so there are fewer GPIO pins. Two Three and Four are continually written to the screen, with no change in behaviour when any of the buttons are depressed. Do you have any ideas?

**Comment by shawaj** [comment]
Yes, the buttons are on pins 36, 37, 38 and 40 so will not work on a Pi 1 with the buttons script unfortunately.
