### ISSUE TITLE
Update papirus-buttons for PaPiRus Zero (or add new script for zero version)

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#40]
Update papirus-buttons for PaPiRus Zero (or add new script for zero version)

**Comment by digithree** [comment]
Bump this. There's 5 buttons on the PaPiRus 2.0" for Zero model. In the meantime, what are the GPIO pins for them?

**Comment by digithree** [comment]
Pin mapping for PaPiRus Zero v1.2 (tested on 2.0" model): 26, 19, 20, 16, 21

I've made the suggested change to the papirus-buttons python script demo and made a pull request for this. I did not add a new script, but modified the existing one to add command line option for Zero

**Comment by francesco-vannini** [comment]
This has been implemented in #79
