### ISSUE TITLE
Add details about RTC / hwclock enabling

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#42]
Add details about RTC / hwclock enabling using config.txt for HAT version:

```
Name:   i2c-rtc
Info:   Adds support for a number of I2C Real Time Clock devices
Load:   dtoverlay=i2c-rtc,<param>=<val>
        mcp7940x                Select the MCP7940x device

```

Use following to load RTC driver for our RTC MCP7940N-I/SN:
`dtoverlay=i2c-rtc,mcp7940x`

In future hardware versions enable auto-config using device tree if possible.

Also need documentation surrounding using hwclock functionality - see [here](https://afterthoughtsoftware.com/products/rasclock) for reference

**Comment by francesco-vannini** [comment]
This has been done in #55
