### ISSUE TITLE
python 3 compatability (on pi zero if it matters)

### ISSUE THREAD

**Issue by pootle** [PiSupply/PaPiRus#52]
The cli things work OK, but if i run python3 and
   import papirus
then help(papirus) gives
`Help on package papirus:

NAME
    papirus

PACKAGE CONTENTS

FILE
    (built-in)

(END)
`
so not a lot works!

**Comment by shawaj** [comment]
this is not working on python3.

Can you not just use python 2.7? 

Or are you saying python3 is default on Pi Zero?

**Comment by pootle** [comment]
Its not default as built, but I use Python3 whenever possible, 'cos of the better language facilities and improved libraries

**Comment by shawaj** [comment]
See #26 also

**Comment by tvoverbeek** [comment]
See the python2-and-3 branch. The same code will run under both Python2 and Python3.
Branch will soon be merged into master.
Closing the issue.
