### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by ChrisHaPunkt** [PiSupply/PaPiRus#57]
Hi all,
do not get this to work on my Raspberry Pi 3B model. 
Same steps on Raspi 2 and everything is working fine...

The install script running through as normal.
On console execution:
`pi@raspberrypi:~ $ sudo papirus-write "Test"`
`Writing to Papirus.......`
`Finished!`
But there is no update on the screen, just blank.
Someone get this to work on a Raspberry Pi 3?

**Comment by auyongcheemeng** [comment]
I dont think the PaPiRus board works for the raspberry pi 3. the pin out for the pogo pin does not match for the Pi 3.

(For version 1.8) Not sure if the board you have have been revised

[board pics](http://imgur.com/a/uVVQd)

**Comment by ChrisHaPunkt** [comment]
I'm running rev 1.9 where a support for the Pi 3 should be given (see pic at bottom, where u can see on the front left of the board the additional pogo pin for matching Pi3)

But I don't think the pogo pin is necessary for running the board. 
I removed the pogo pin for testing on the Pi 2 and it also works well.
Nevertheless i connected the pogo pin port on the Raspberry Pi 3, what didn't change a thing :(

![img_20160913_102708](https://cloud.githubusercontent.com/assets/4389395/18466617/b3ba9364-799c-11e6-8def-b5283b2f33c8.jpg)

**Comment by shawaj** [comment]
Have you got SPI and I2C turned on?

Thanks

**Comment by shawaj** [comment]
The v1.9 has Pogo pin locations for B+/2B/A+ and 3B so you can use with
either but this is not required to update the screen.

Thanks,
Aaron

**Comment by ChrisHaPunkt** [comment]
Yes, both enabled:
![bildschirmfoto 2016-09-13 um 11 11 40](https://cloud.githubusercontent.com/assets/4389395/18468142/e708b81c-79a2-11e6-8776-96d887fc6aee.png)

**Comment by shawaj** [comment]
Can you try command i2cdetect -y 1 ?

Does this find anything?

Thanks

**Comment by ChrisHaPunkt** [comment]
I'l give it a try.

For comparison, the loaded modules on the working Pi 2:
![bildschirmfoto 2016-09-13 um 11 31 52](https://cloud.githubusercontent.com/assets/4389395/18468833/0017d826-79a6-11e6-903e-b38089eab07d.png)

**Comment by ChrisHaPunkt** [comment]
I guess nothing has been found (Pi3):
![bildschirmfoto 2016-09-13 um 11 37 35](https://cloud.githubusercontent.com/assets/4389395/18468955/87533740-79a6-11e6-973b-bf7d876033d7.png)

**Comment by ChrisHaPunkt** [comment]
As aspected, not even enabled.
![bildschirmfoto 2016-09-13 um 11 41 06](https://cloud.githubusercontent.com/assets/4389395/18469128/31198d4c-79a7-11e6-8515-f35350bf2755.png)

But working fine:
![bildschirmfoto 2016-09-13 um 11 42 32](https://cloud.githubusercontent.com/assets/4389395/18469131/3724b3ec-79a7-11e6-855b-5145238723ad.png)
![img_20160913_114221](https://cloud.githubusercontent.com/assets/4389395/18469142/4520b86a-79a7-11e6-9f42-f17424d36ae4.jpg)

**Comment by shawaj** [comment]
Have you got another Pi 3 to try with?

Maybe the Pi 3 is the problem?

Does i2c command work on Pi 3?

Thanks

On 13 Sep 2016 1:43 pm, "Christian Heinrichs" <notifications@github.com>
wrote:

As aspected, not even enabled.
[image: bildschirmfoto 2016-09-13 um 11 41 06]
<https://cloud.githubusercontent.com/assets/4389395/18469128/31198d4c-79a7-11e6-8515-f35350bf2755.png>

But working fine:
[image: bildschirmfoto 2016-09-13 um 11 42 32]
<https://cloud.githubusercontent.com/assets/4389395/18469131/3724b3ec-79a7-11e6-855b-5145238723ad.png>
[image: img_20160913_114221]
<https://cloud.githubusercontent.com/assets/4389395/18469142/4520b86a-79a7-11e6-9f42-f17424d36ae4.jpg>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/57#issuecomment-246630006>, or mute
the thread

**Comment by ChrisHaPunkt** [comment]
Not at hand, but i'll ask a friend of mine.
Can u confirm that it is running on another Pi 3?

**Comment by shawaj** [comment]
Yes we have it running on many Pi 3 boards :-)

**Comment by tedjackyx** [comment]
mine is 1.8
I just try on PI 3 and PI 2, both are not working.
I have no idea what happen on that...

**Comment by shawaj** [comment]
Did it work before?

What error messages are you seeing?

Thanks

**Comment by tedjackyx** [comment]
Hi, I didn't see any error,
i am useing:  
sudo papirus-write "123"
And got same response(commend) as you.

**Comment by shawaj** [comment]
So what happens when you type that command and then hit enter? It works OK
or not?

**Comment by ChrisHaPunkt** [comment]
May be some relations to this issue with latest jessie release on pi3:
https://www.raspberrypi.org/forums/viewtopic.php?f=37&t=147291

I'll investigate further...

**Comment by ChrisHaPunkt** [comment]
Since a simple loopback test failed on my Pi3, I tried the application on a new RPi3 and everything worked out-of-the-box ...
Going to send my RPi3 back .
Thanks all
