### ISSUE TITLE
Missing dependencies, installer not working fully and some demo problems.

### ISSUE THREAD

**Issue by tchilton** [PiSupply/PaPiRus#59]
On a brand new Raspberry Pi 3 with the  2016-05-27-raspbian-jessie-lite.img image loaded, the installer fails to install correctly using the instructions listed here.   

I followed the python API and method 1 (papirus-setup) as root. The install fails because of some missing dependencies and the script has some bugs, it checks that you are root, then forces all commands to sudo which is unnecessary as you are already superuser at that point.  The apt-get commands then fail to install the add-ons. 

I had to do the following to install correctly. 

apt-get install git fuse libfuse-dev fonts-freefont-ttf
Then run papirus-setup.

I note that install method 2 DOES install libfuse-dev, hence the two methods are not consistent.

Once this is done, the panel installed correctly.

I also notice that some of the demos are missing
papirus-system
papirus-framepush
papirus-snakes

Similarly, the papirus-temp demo does not work unless bc and i2c-get are installed (apt-get install bc i2c-tools)

**Comment by francesco-vannini** [comment]
Libfuse is installed by the main script and the need for enabling i2c has been added to the instructions.
I have tested the automated installation and the preliminary steps successfully.
The demos that are currently not implemented are on the list of the functionality to be developed.
