### ISSUE TITLE
Add framebuffer mirror

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#71]
Add framebuffer mirror example

**Comment by shawaj** [comment]
Take a look at issue #24 also

**Comment by francesco-vannini** [comment]
This is liked to https://github.com/repaper/gratis/issues/68 and https://github.com/raspberrypi/linux/pull/2119

**Comment by shawaj** [comment]
We should try this out tomorrow!

**Comment by francesco-vannini** [comment]
I have tested it yesterday at the office but only managed to run the clock example from https://github.com/notro/pydrm More than this I could not really understand what to do really.

**Comment by tvoverbeek** [comment]
Just did rpi-update and added the papirus overlay for the 2.7 screen.

The 2 demos (CounterDemo and clock27) work.
clock27 uses full update every minute (since it does drm.enable() and
drm.disable() around each update)
CounterDemo uses partial update since it does not do drm.disable() between
updates.

Note: the speed of CounterDemo is limited by the temperature dependent
stage-time
(same as in current repaper/gratis fuse implementation). Could reach higher
speeds
(as in the Pervasive video https://www.youtube.com/watch?v=enzUbiSWenQ) if
we could
set the stage-time directly independent of temperature.

The papirus module and the libfuse (/dev/epd) one cannot co-exist.
The kernel module also claims the lm75b interface, so any access from the
libfuse one fails.
This is the same issue as with the kernel rtc module loaded.

That is all for now

**Comment by notro** [comment]
@tvoverbeek
I'm picking up from your comment in https://github.com/notro/tinydrm/issues/2 here so I don't clutter that announcement thread.

How are most people using these displays on the Raspberry Pi, as clocks?

**Comment by tvoverbeek** [comment]
@notro 
Clock is only a demo app. Real applications are things like weather stations, twitter feed monitors, news and sports tickers, and anything else you can dream up.
Certainly a combination of text and (small) pictures/icons is a common application.
Hence my request to use dithering in the conversion to mono. It is a pity to throw away all the picture info you still have in the 8-bit grayscale after conversion from xRGB8888.
As far as I know dithering an already B/W image leaves the image unchanged.

Maybe Aaron, @shawaj and Francesco, @francesco-vannini can chime in with other application examples.

I am trying to demo this (adding F-S dithering to the repaper module) using your development instructions for RPi (https://github.com/notro/tinydrm/wiki/board:-Raspberry-Pi)

**Comment by notro** [comment]
Here's a driver with dithering (before I decided against it) that didn't go anywhere: https://github.com/notro/tinydrm/blob/master/el320-240-36-hb-spi.c

You mentioned fbdev apps like fbcon and fbi, one thing to keep in mind is that the controller stays enabled  by default for 30 minutes before blanked, unless explicitly disabled.
Writing to /sys/class/graphics/fb1/blank between updates is one possibility.

**Comment by tvoverbeek** [comment]
Thanks. Saves me some time. You did not use the 'real' Floyd-Steinberg, but the so called false one.
See http://www.efg2.com/Lab/Library/ImageProcessing/DHALF.TXT.
Will try with both variants and let you know the results.
Yes, I am aware of the console-blanking issue (have been bitten several times by it)

**Comment by notro** [comment]
> You did not use the 'real' Floyd-Steinberg, but the so called false one.

I didn't know that, I just copied from an fbtft driver. I wasn't very impressed by the result, so that's probably the reason. But then again, I didn't know what to expect :-)

**Comment by notro** [comment]
I have checked with the drm maintainer and we can't do software dithering in the kernel: https://lists.freedesktop.org/archives/dri-devel/2017-August/149243.html

**Comment by tvoverbeek** [comment]
Noralf,
Tack för fråga på DRM listan / Thanks for asking on the DRM list.

I still think it is a pity for our use case, but I understand Daniel Vetter's reasoning.
Will try to find a user-space approach for e.g. displaying the pi-camera image as a dithered
gray-scale image on the Papirus displays.
I just got the real Floyd-Steinberg dithering (2 x 3 diffusion matrix) working in repaper.c yesterday.
Looks pretty good on the 2.7" display.

Anyway, thanks again for all your efforts / Tack så mycket för all dina ansträngningar.

Ton van Overbeek
PS Lived, studied and worked for 6 years in Sweden at Linköpings University

**Comment by notro** [comment]
> PS Lived, studied and worked for 6 years in Sweden at Linköpings University

You picked up the language I see :-)

**Comment by shawaj** [comment]
Think we can close this issue as it is fixed in https://github.com/PiSupply/PaPiRus/blob/master/bin/papirus-fbcopy ?

**Comment by tvoverbeek** [comment]
Agreed

**Comment by shawaj** [comment]
Fixed in #173
