### ISSUE TITLE
Add test mode - and crack/screen break detection

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#72]
Add test mode - and crack/screen break detection

**Comment by francesco-vannini** [comment]
Crack/screen break added to main EPD repo - https://github.com/repaper/gratis/pull/60

However still need to add an overarching papirus-test script here, for testing things like i2c/spi etc for helping debug customer issues etc

**Comment by francesco-vannini** [comment]
A new script has been created in #135
