### ISSUE TITLE
No longer need root

### ISSUE THREAD

**Issue by t3chguy** [PiSupply/PaPiRus#76]
Later versions of Raspbian allow access to gpio/i2c/spi without root permissions by default so the root check should be removed from the scripts

**Comment by francesco-vannini** [comment]
Same as part of what discussed in issue #55

**Comment by shawaj** [comment]
We've decided to leave it in incase people are running on older versions of
Raspbian and/or to do a check to see what version they're running.

**Comment by francesco-vannini** [comment]
Closing this as has been sorted in #77 and #79 
Thanks
