### ISSUE TITLE
Doesn't work on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by fangfufu** [PiSupply/PaPiRus#81]
I have a PaPiRus Zero (PZ). I recently bought a new Raspberry Pi Zero W (RPi 0W). The commands used to control PZ successfully execute on RPi 0W. However, PZ doesn't react to it. I plug my PZ on my old RPi 0 along with the same microSD card, PZ works fine. So I am certain that there is some sort of compatibility issue.

**Comment by shawaj** [comment]
@fangfufu have you installed the software on the Pi Zero W and turned I2C and SPI on?

Because we have tested it with the Pi Zero W and it works perfectly

**Comment by shawaj** [comment]
@fangfufu - picture of it working with Pi Zero Wireless has - http://m.imgur.com/eYbnkQb

(Picture courtesy of @francesco-vannini )

**Comment by shawaj** [comment]
*here

**Comment by fangfufu** [comment]
@shawaj , I have installed the software in Pi Zero W and turned the I2C and SPI on. The same microSD card works fine on my old Pi Zero.

**Comment by shawaj** [comment]
Please try with a fresh installation of Raspbian on the Pi Zero W as it's
working fine for us.

Thanks

On 13 Mar 2017 9:44 pm, "Fufu Fang" <notifications@github.com> wrote:

@shawaj <https://github.com/shawaj> , I have installed the software in Pi
Zero W and turned the I2C and SPI on. The same microSD card works fine on
my old Pi Zero.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/81#issuecomment-286253531>, or mute
the thread

**Comment by fangfufu** [comment]
@shawaj I have tried flash a new microSD card with Raspbian Lite, and re-installed everything. It still doesn't work.

**Comment by shawaj** [comment]
Try Raspbian full version instead of Raspbian lite :-)

**Comment by fangfufu** [comment]
I don't understand why Raspbian full would make a difference, compared
to Raspbian lite.

Before I flash my microSD card again, is there a better way to diagnose
this problem? Where can I get the error messages?

**Comment by shawaj** [comment]
Raspbian full and lite have many different packages installed by default,
among other notable differences.

It's best to try a like for like swap so that we can be 100% sure.

Thanks

**Comment by fangfufu** [comment]
I have just flashed Raspbian full, and reinstall the drivers. It still
doesn't work... Once again, the same MicroSD card work for my Raspberry
Pi Zero... ``cat /dev/epd/temperature`` works though.

**Comment by shawaj** [comment]
Seems like it should be working then if it's appearing.

I can't see an issue.

**Comment by fangfufu** [comment]
If I understand it correctly, the temperature sensor uses I2C bus,
whereas the display itself uses the SPI bus... Anyway, it is not
working. Please tell me how to diagnose this. There is definitely an
issue...

**Comment by fangfufu** [comment]
Could you send me your microSD card image? You could Dropbox / Google Drive it.

**Comment by fangfufu** [comment]
I have two Raspberry Pi Zero W lying around. I have tried them both, none of them work. It works fine with the original Rasbperry Zero though.

**Comment by shawaj** [comment]
As said, start from a fresh Raspbian full installation and follow the
instructions to install everything including turning in spi and i2c.

If it works on one, it works on all. They are pin compatible.

Please make sure also that you have a good connection. Some headers for the
Pi Zero are not very well made for example - make sure it's one who square
pins not flat pins.

Thanks

**Comment by fangfufu** [comment]
> As said, start from a fresh Raspbian full installation and follow the
> instructions to install everything including turning in spi and i2c.
>
I have done exactly that.
> Please make sure also that you have a good connection. Some headers
> for the
> Pi Zero are not very well made for example - make sure it's one who square
> pins not flat pins.
I have soldered the header for all the Raspberry Pi Zeros that had been
tested.

Anyway, so far I have tested on 2 Raspberry Pi Zero Ws,and 1 Raspberry
Pi Zero. It works on my Raspberry Pi Zero, but not Zero Ws.

**Comment by shawaj** [comment]
Seems like a loose connection is possible. Can you send a picture of the
header you have soldered in?

Thanks

**Comment by fangfufu** [comment]
I really don't think there is any soldering problem. Do you not have any ideas on how to diagnose epd-fuse daemon? 

![20170314_022436](https://cloud.githubusercontent.com/assets/2323403/23883305/07314a7e-085e-11e7-930d-1f53f4fcc029.jpg)

**Comment by shawaj** [comment]
Unless you installed it wrong, EPD fuse should be working fine. It's no
different on pi zero to pi zero w.

Please send a picture of the header itself, not just the underside.

Thanks

**Comment by fangfufu** [comment]
I haven't installed it wrong, because it is on the same microSD card. It is a fresh installation too. I have put my RPi ZW back into the enclosure. 
![20170314_024351](https://cloud.githubusercontent.com/assets/2323403/23883616/2e8e8c4c-0860-11e7-8e42-c7db8bb6dbbb.jpg)

**Comment by shawaj** [comment]
Are you sure it's not the enclosure clashing?

You should also use a *different* SD card for the Pi Zero to the Pi Zero W
for testing purposes just to rule out any issues there.

It seems to either be a connection issue or a software installation issue.

Thanks

**Comment by fangfufu** [comment]
I have not been using that enclosure when I am using the Papirus Zero. I
have put my RPi ZW back in that enclosure, because I don't think I am
going to get Papirus working with RPi ZW.

I don't see how using a different SD card for Pi Zero and Pi Zero W
would rule out any issue, other than adding in more variable. I ran your
script under under RPi ZW, it didn't work. Then I put the card in RPi Z,
it worked. I have also tested my Papirus Zero on two separate RPi ZW,
the both didn't work consistently . So I think it is clear that there is
some sort of compatibility issue.

Why don't you send me your SD card image to rule out software problem?

**Comment by shawaj** [comment]
Because we've already tested it and it works flawlessly :-)

**Comment by fangfufu** [comment]
And before you blame "enclosure clash", the first image actually has Papirus attached to my RPi ZW, with the Papirus at the bottom... 

Anyway, I give up.

**Comment by shawaj** [comment]
We will try again tomorrow with some more Pi Zero Ws if we can get our
hands on a couple more.

See if​ we can reproduce anything.

On 14 Mar 2017 3:08 am, "Fufu Fang" <notifications@github.com> wrote:

And before you blame "enclosure clash", the first image actually has
Papirus attached to my RPi ZW, with the Papirus at the bottom...

Anyway, I give up.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/81#issuecomment-286309151>, or mute
the thread

**Comment by shawaj** [comment]
We have tested with every Raspberry Pi Zero Wireless we have in the office and it works with all of them using the instructions provided here.

So it's not an issue with our software or with Raspbian.

It must either be a loose connection, that you have not installed the software correctly or that you have broken some of the GPIO pins on your Pi Zero Ws from soldering them too hot or something.

**Comment by shawaj** [comment]
@francesco-vannini also tested the board by installing the software on a pi zero normal, and then transferring the PaPiRus Zero and the SD card to the Pi Zero Wireless and that worked also. So again it must be an issue with one of the things mentioned above

**Comment by fangfufu** [comment]
Well, I performed SPI loopback documented here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md

It worked fine.

**Comment by shawaj** [comment]
Glad to hear you got it working. Great news :-)

**Comment by fangfufu** [comment]
No, it still doesn't work. : ( I can only confirmed that the SPI bus
works, and the epd-fuse freeze up my serial console.

**Comment by fangfufu** [comment]
I am getting my 3rd Raspberry Pi Zero W... If it works, I will let you guys know...

**Comment by shawaj** [comment]
Are you sure you are using a clean Raspbian install? With nothing else
installed?

And you're using the one line install from our main GitHub readme?

**Comment by fangfufu** [comment]
Yes, I am 100% sure. I am getting a new Raspberry Pi Zero W, because the
one I have right now refuse to enter gadget mode. So the supplier
allowed me to return it.

**Comment by shawaj** [comment]
Hmm strange. Maybe you just had really bad luck and it was a faulty one :-)

**Comment by fangfufu** [comment]
Surely I can't be unlucky enough to get two faulty Raspberry Pi Zero W
in a row, right? :(

**Comment by shawaj** [comment]
Dunno but we've got the software working on pi zero wireless and you said
the board is working on pi zero.

So points to a software configuration or pi zero issue on your end. I can't
see what else it could be

**Comment by shawaj** [comment]
@fangfufu just had a thought - are you trying to connect to this through serial console and use the Pi Zero Wireless at the same time? If so I don't think that will work.

Try it with a screen, keyboard, mouse etc (or over SSH) first and then let us know if that sorts your issue.

**Comment by fangfufu** [comment]
I have been trying to use the Raspberry Pi Zero gadget mode. Does that
change things?

**Comment by fangfufu** [comment]
I have been using gadget mode with Raspberry Pi Zero. Papirus works fine.

**Comment by shawaj** [comment]
Perhaps you could try with Pi Zero W not in gadget mode (using it just normally with a screen and KB/mouse) and report back

**Comment by shawaj** [comment]
then we can try to isolate the issue

**Comment by fangfufu** [comment]
It still doesn't work with Pi Zero W not in gadget mode. Is there any sort of logs produced by the driver?

**Comment by shawaj** [comment]
Must be a loose connection then or broken GPIO pins. Can't really see how
it could be anything else

**Comment by fangfufu** [comment]
So which pin is broken then? Can the driver tell?

**Comment by shawaj** [comment]
No sorry. There's not any more we can do to help. You will have to work
that out yourself.

But we are 100% sure it works on pi zero wireless as we have them running
here and the PaPiRus itself works as you said.

As said, start from a FRESH Raspbian / NOOBS installation and follow the
install one line instructions on the main readme of this GitHub. Do not
install any other software or do anything other than enable I2C and SPI and
it will work assuming that your Pi Zero is not faulty or the GPIO pins have
not been damaged.

Thanks

**Comment by fangfufu** [comment]
Hey, I got my 3rd Pi Zero W. Now everything is working. It turns out that my 2nd Pi Zero doesn't have 5.0 on one of the pin used by Papirus. This whole experience has been stressful. I can't believe that my two Pi Zero Ws from two different suppliers are slightly broken in different ways...

**Comment by shawaj** [comment]
Perfect, glad you have it working now

On 15 Mar 2017 12:09 pm, "Fufu Fang" <notifications@github.com> wrote:

Hey, I got my 3rd Pi Zero W. Now everything is working. It turns out that
my 2nd Pi Zero doesn't have 5.0 on one of the pin used by Papirus. This
whole experience has been stressful. I can't believe that my two Pi Zero Ws
from two different suppliers are slightly broken in different ways...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/PiSupply/PaPiRus/issues/81#issuecomment-286723151>, or mute
the thread

**Comment by amkeener** [comment]
Just a heads up... I experienced this same issue on two Raspberry Pi Zero Ws... The only solution that worked for me was to disable both serial options in raspi-config (serial login shell and serial port hardware).
