### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by daxx2k** [PiSupply/PaPiRus#84]
Hi there, I would like to use the large 2.7inch display in portrait mode, there is any way I can write and display text in that way? thanks!

**Comment by shawaj** [comment]
This is an interesting request that we've not had before. Perhaps @BenScarb and @francesco-vannini might have some ideas about how to do this?

In the meantime you could perhaps turn the text into an image and have it rotated?

**Comment by shawaj** [comment]
Closing this issue as issue #90 has been opened but it's more generic and think more relevant to have it so that you can rotate the screen.

In framebuffer / fbtft this can be done by specifying clockwise rotations from standard - 90, 180, 270 - think this would be our best bet

**Comment by daxx2k** [comment]
thanks for looking into that!

**Comment by shawaj** [comment]
@daxx2k - if you go to that other issue linked above and subscribe to it, then you will get an update once we build in the support :-)
