### ISSUE TITLE
PaPiRus textpos does only a partial update?

### ISSUE THREAD

**Issue by shawaj** [PiSupply/PaPiRus#91]
PaPiRus textpos does only a partial update, so if there's something over the screen.

@BenScarb @francesco-vannini do you think it would be better to have it with a full update, or have an option to do either a full or partial update? I like the idea of a partial update as it allows you to write text over an image but sometimes you just want text...

What do you think?

**Comment by francesco-vannini** [comment]
I think textpos.py should default to full update and have an option for partial
Changed textpos.py to only do full updates in #94 until the option is introduced.

**Comment by shawaj** [comment]
Yes, agreed @francesco-vannini - the partial should be an argument. This should probably be the case with all example scripts

**Comment by francesco-vannini** [comment]
@BenScarb this has been dealt with right?

**Comment by francesco-vannini** [comment]
I think this could be closed

**Comment by shawaj** [comment]
Did we fix it already?

**Comment by shawaj** [comment]
@benscarb was this fix part of #105?

**Comment by BenScarb** [comment]
I do believe it was, commits on the 4th of Apr allow for partial or full updates to be done.  Defaults to Full update.
https://github.com/PiSupply/PaPiRus/pull/105#commits-pushed-609ddbc

**Comment by francesco-vannini** [comment]
Thanks @BenScarb, closing this up.
