### ISSUE TITLE
Papirusimage.write only takes 2 args

### ISSUE THREAD

**Issue by saty9** [PiSupply/PaPiRus#99]
the readme docs describe a 3 argument version of papirusimage.write
image.write('/path/to/image', 20, (10, 10) )
however that doesn't seem to exist.

**Comment by shawaj** [comment]
@francesco-vannini can you shed any light on this?

Is there a 3 argument version?

**Comment by GregLukosek** [comment]
This is very disappointing. Why does doc describing how to use methods that aren't existing?

**Comment by GregLukosek** [comment]
to clarify. PapirusImage() does not contain any method except simple write that draws image full screen

**Comment by shawaj** [comment]
This is in a PR I believe which we will be looking at this week.

**Comment by tvoverbeek** [comment]
See commit 48ca0fc on the papirus2-and-3 branch.
image.py and README updated.
Something similar to the not-implemented method in PapirusImage is available in PapirusComposite.
Closing this issue.
